"""like

Revision ID: f7922b445c5e
Revises: 460ae953628d
Create Date: 2018-05-01 02:07:43.571822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7922b445c5e'
down_revision = '460ae953628d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liker', sa.String(length=64), nullable=True),
    sa.Column('po', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liker'], ['user.username'], ),
    sa.ForeignKeyConstraint(['po'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
