"""comments

Revision ID: 100ad9a18614
Revises: bf1e4b795a19
Create Date: 2018-04-16 16:38:20.776689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100ad9a18614'
down_revision = 'bf1e4b795a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_group_groupname', table_name='group')
    op.create_index(op.f('ix_group_groupname'), 'group', ['groupname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_groupname'), table_name='group')
    op.create_index('ix_group_groupname', 'group', ['groupname'], unique=1)
    op.drop_table('comment')
    # ### end Alembic commands ###
