"""messages

Revision ID: 2477052aaf76
Revises: a7562ffbbdee
Create Date: 2018-04-17 23:00:02.597489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2477052aaf76'
down_revision = 'a7562ffbbdee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=64), nullable=True),
    sa.Column('msg', sa.String(length=700), nullable=True),
    sa.Column('reciever', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['reciever'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_msg'), 'message', ['msg'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_msg'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
