"""event

Revision ID: 2b7b40d31723
Revises: cf882d0dce70
Create Date: 2018-04-29 06:11:40.250174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7b40d31723'
down_revision = 'cf882d0dce70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingroup', sa.Column('event', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingroup', 'event')
    # ### end Alembic commands ###
