"""post in group

Revision ID: a7562ffbbdee
Revises: 100ad9a18614
Create Date: 2018-04-17 18:33:33.320775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7562ffbbdee'
down_revision = '100ad9a18614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('myuser', sa.Integer(), nullable=True),
    sa.Column('gp', sa.String(length=64), nullable=True),
    sa.Column('pg', sa.String(length=140), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gp'], ['group.groupname'], ),
    sa.ForeignKeyConstraint(['myuser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingroup_time'), 'ingroup', ['time'], unique=False)
    op.drop_index('ix_Groups_groupname', table_name='Groups')
    op.drop_table('Groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('userid', sa.INTEGER(), nullable=True),
    sa.Column('groupname', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], )
    )
    op.create_index('ix_Groups_groupname', 'Groups', ['groupname'], unique=1)
    op.drop_index(op.f('ix_ingroup_time'), table_name='ingroup')
    op.drop_table('ingroup')
    # ### end Alembic commands ###
